# Generated by Django 2.2.4 on 2019-08-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boastroast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('Boast', 'Boast'), ('Roast', 'Roast')], default='Boast', max_length=5),
        ),
    ]
